package proyecto.pkgfinal.progra.ii;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Leonardo Vargas
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUISesion = new javax.swing.JButton();
        GUIUsuario = new javax.swing.JTextField();
        GUIPassword = new javax.swing.JTextField();
        GUIAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GUISesion.setText("Iniciar sesion");
        GUISesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUISesionMouseClicked(evt);
            }
        });
        GUISesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUISesionActionPerformed(evt);
            }
        });

        GUIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIUsuarioActionPerformed(evt);
            }
        });

        GUIAgregar.setText("Agregar ");
        GUIAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUIAgregarMouseClicked(evt);
            }
        });
        GUIAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(GUISesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(GUIAgregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUIUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUIPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUIPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addComponent(GUISesion)
                .addGap(29, 29, 29)
                .addComponent(GUIAgregar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIUsuarioActionPerformed

    private void GUIAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUIAgregarActionPerformed

    private void GUISesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUISesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUISesionActionPerformed

    private void GUISesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUISesionMouseClicked
        
        String nombre = null;
        int cedula;
        int edad;
        String horario= null;
        String usuario = null;
        String password = null;
        int cont = 0;
         try{
            File fichero_entrada;
            File fichero_salida = null;
           
            fichero_entrada = new File ("RegistroPersonal\\"+GUIUsuario.getText()+".txt");

            //Si no hay fichero de entrada no hacemos proceso de cálculo
            if (!fichero_entrada.exists()) {
                System.out.println ("No existe el fichero de entrada especificado"); 
            }

            else { //Sí existe un fichero de entrada y se procesa para su cálculo
                //Extracción de datos del fichero de entrada ejemplo aprenderaprogramar.com
                Scanner scan1 = new Scanner (fichero_entrada);
                ArrayList<String> datosDeEntrada = new ArrayList<String>();
                int contador = 0;
                //scan1.hasNext()
                while (contador<3){
                    String lineaExtraida = scan1.nextLine();
                    datosDeEntrada.add(lineaExtraida);
                    contador++;
                }

                //System.out.println("El número de líneas en el fichero de entrada es: " + contador);

                String [] datosDeEntradaArray = new String[contador];

                for (int i=0; i<datosDeEntradaArray.length; i++){
                    datosDeEntradaArray[i] = datosDeEntrada.get(i);
                    if(i==0){
                         nombre = datosDeEntradaArray[i];
                    }
                  
                    if(i==1){
                         password = datosDeEntradaArray[i];
                    }
                    //System.out.println("Mostrando línea en fichero " + (i+1) + ": " + datosDeEntradaArray[i]);
                }

            }
        }catch (Exception e) {System.out.println ("Se ha producido un error " +e + ". Revise argumentos y datos");}
        
                
        if(GUIPassword.getText().equals(password)==true && GUIUsuario.getText().equals(usuario)==true){
            JOptionPane.showMessageDialog(null, "Bienvenido(a) "+ nombre);
          //Aqui va el enlace al menu
            PantallaPrincipal jmenu = new PantallaPrincipal();
            jmenu.setVisible(true);
            IniciarSesion.this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Error de credenciales");
            GUIPassword.setText(null);
            GUIUsuario.setText(null);
                cont++;                             
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_GUISesionMouseClicked

    private void GUIAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUIAgregarMouseClicked
         RegistroChofer TRegistro = new RegistroChofer();
        TRegistro.setVisible(true);
        this.setVisible(false);   

// TODO add your handling code here:
    }//GEN-LAST:event_GUIAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUIAgregar;
    private javax.swing.JTextField GUIPassword;
    private javax.swing.JButton GUISesion;
    private javax.swing.JTextField GUIUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
